"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { createAuthService } from "@saas-ui/supabase";

const inter = Inter({ subsets: ["latin"] });

import type { Metadata } from "next";
import {
  AuthProvider,
  useAuth,
  useCurrentUser,
  useLogin,
  useSignUp,
  useOtp,
} from "@saas-ui/auth";

import { createClientComponentClient } from "@supabase/auth-helpers-nextjs";

const supabase = createClientComponentClient();

const authService = createAuthService(supabase);

//@ts-ignore
const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(authService);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider {...authService}>{children}</AuthProvider>
      </body>
    </html>
  );
}
